export const CHOICE_PAGE = "CHOICE_PAGE";
export const COURSE_PAGE = "COURSE_PAGE";
export const QUIZZ_PAGE = "QUIZZ_PAGE";
export const QUIZZ_PENDULE_SIMPLE = "QUIZZ_PENDULE_SIMPLE";
export const QUIZZ_PENDULE_ELASTIQUE_EQUILIBRE = "QUIZZ_PENDULE_ELASTIQUE_EQUILIBRE";
export const QUIZZ_PENDULE_ELASTIQUE_COMPRIMER = "QUIZZ_PENDULE_ELASTIQUE_COMPRIMER";
export const QUIZZ_PENDULE_ELASTIQUE_ETIRER = "QUIZZ_PENDULE_ELASTIQUE_ETIRER";
