export const CHOICE_PAGE = "CHOICE_PAGE";
export const COURSE_PAGE = "COURSE_PAGE";
export const QUIZZ_PAGE = "QUIZZ_PAGE";
export const QUIZZ_PENDULE_SIMPLE = "QUIZZ_PENDULE_SIMPLE";
export const QUIZZ_PENDULE_ELASTIQUE = "QUIZZ_PENDULE_ELASTIQUE";
